### LISTAR TODOS OS ALUNOS
GET http://localhost:3000/api/students
Content-Type: application/json

### LISTAR ALUNO POR ID
GET http://localhost:3000/api/students/b816470f-97fa-48e3-b7ce-c940c7465b26
Content-Type: application/json

### CADASTRAR UM NOVO ALUNO
POST http://localhost:3000/api/students
Content-Type: application/json

{
  "name": "Diego",
  "surname": "Costa",
  "email": "diegocosta@email.com",
  "age": 30
}

### ATUALIZAR UM NOVO ALUNO
PUT http://localhost:3000/api/students/99ef179a-89cf-46e9-8bec-192958a1bcd4
Content-Type: application/json

{
  "email": "atualizado@gmail.com"
}

### REMOVER UM ALUNO
DELETE http://localhost:3000/api/students/b816470f-97fa-48e3-b7ce-c940c7465b26
Content-Type: application/json