### LISTAR TODOS OS ALUNOS
GET http://localhost:3000/api/students
Content-Type: application/json

### LISTAR ALUNO POR ID
GET http://localhost:3000/api/students/84e55958-edec-4867-8a80-85efb975c9a7
Content-Type: application/json

### CADASTRAR UM NOVO ALUNO
POST http://localhost:3000/api/students
Content-Type: application/json

{
  "name": "Herlon",
  "surname": "Costa",
  "email": "herloncosta@email.com",
  "age": 28
}

### ATUALIZAR UM NOVO ALUNO
PUT http://localhost:3000/api/students/8d4838d0-8f65-4140-bc86-ecc8d5f34175
Content-Type: application/json

{
  "email": "atualizado@gmail.com"
}

### REMOVER UM ALUNO
DELETE http://localhost:3000/api/students/8d4838d0-8f65-4140-bc86-ecc8d5f34175
Content-Type: application/json