### VARIÁVEIS
@apiurl = http://localhost:4000/api/users

### CADASTRAR UM NOVO USUÁRIO
POST {{apiurl}}/auth/signup
Content-Type: application/json

{
  "username": "Herlon Costa",
  "password": "herloncosta",
  "email": "herloncosta@email.com"
}

### ATUALIZAR UM NOVO USUÁRIO
PUT {{apiurl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5MDhkYTFlLWM2MGUtNDJmNS04MTQwLTUwZmQ0ZWY5YzA4OSIsInVzZXJuYW1lIjoiSGVybG9uIENvc3RhIiwiZW1haWwiOiJoZXJsb25jb3N0YUBlbWFpbC5jb20iLCJpYXQiOjE3MjgyMzIzOTYsImV4cCI6MTcyODIzNTk5Nn0.9t-5NNAcdI67_q5XgY0nsm0w2wxZqpntPeZdqyjRhkc

{
  "username": "Herlon Costa",
  "password": "herlonsantos",
  "email": "herloncosta@email.com"
}

### REMOVER UM USUÁRIOS
DELETE {{apiurl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5MDhkYTFlLWM2MGUtNDJmNS04MTQwLTUwZmQ0ZWY5YzA4OSIsInVzZXJuYW1lIjoiSGVybG9uIENvc3RhIiwiZW1haWwiOiJoZXJsb25jb3N0YUBlbWFpbC5jb20iLCJpYXQiOjE3MjgyMzIzOTYsImV4cCI6MTcyODIzNTk5Nn0.9t-5NNAcdI67_q5XgY0nsm0w2wxZqpntPeZdqyjRhkc

### LOGIN
POST {{apiurl}}/auth/signin
Content-Type: application/json

{
  "email": "herloncosta@email.com",
  "password": "herloncosta"
}