### LISTAR TODOS OS USUÁRIOS
GET http://localhost:3000/api/users
Content-Type: application/json

### LISTAR USUÁRIOS POR ID
GET http://localhost:3000/api/users/736bad39-27ee-45d5-b576-8d1213d3f5d1
Content-Type: application/json

### CADASTRAR UM NOVO USUÁRIO
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "Herlon",
  "password": "herloncosta",
  "email": "herloncosta@email.com"
}

### ATUALIZAR UM NOVO USUÁRIO
PUT http://localhost:3000/api/users/fcbe0568-2000-4ead-83ee-e5c9dfbc9e6c
Content-Type: application/json

{
  "username": "Herlon Costa",
  "password": "herloncosta",
  "email": "herloncosta@gmail.com"
}

### REMOVER UM USUÁRIOS
DELETE http://localhost:3000/api/users/fcbe0568-2000-4ead-83ee-e5c9dfbc9e6c
Content-Type: application/json