version: '3'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
